print ("Введите a"); a=int(input())
print ("Введите b");b=int(input())
print ("Введите c");c=int(input())
print ("Введите d");d=int(input())
print ("Введите f");f=int(input())
y=int(f - d)
x=int
if  y== 0 :print("Делить на ноль нельзя")
else : x = ((a*b-c)/(f-d))
print(x)