# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_3 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_3.setMaximumSize(QtCore.QSize(200, 200))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_ip = QtWidgets.QLabel(parent=self.widget_3)
        self.label_ip.setMaximumSize(QtCore.QSize(100, 15))
        self.label_ip.setObjectName("label_ip")
        self.verticalLayout_2.addWidget(self.label_ip)
        self.lineEdit_ip = QtWidgets.QLineEdit(parent=self.widget_3)
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.verticalLayout_2.addWidget(self.lineEdit_ip)
        self.label_port = QtWidgets.QLabel(parent=self.widget_3)
        self.label_port.setMaximumSize(QtCore.QSize(50, 15))
        self.label_port.setObjectName("label_port")
        self.verticalLayout_2.addWidget(self.label_port)
        self.lineEdit_port = QtWidgets.QLineEdit(parent=self.widget_3)
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.verticalLayout_2.addWidget(self.lineEdit_port)
        self.connect_Button = QtWidgets.QPushButton(parent=self.widget_3)
        self.connect_Button.setObjectName("connect_Button")
        self.verticalLayout_2.addWidget(self.connect_Button)
        self.horizontalLayout_3.addWidget(self.widget_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget_2)
        self.textoutput = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textoutput.setReadOnly(True)
        self.textoutput.setObjectName("textoutput")
        self.verticalLayout.addWidget(self.textoutput)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.text_input = QtWidgets.QLineEdit(parent=self.widget)
        self.text_input.setObjectName("text_input")
        self.horizontalLayout.addWidget(self.text_input)
        self.send_Button = QtWidgets.QPushButton(parent=self.widget)
        self.send_Button.setObjectName("send_Button")
        self.horizontalLayout.addWidget(self.send_Button)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Shady"))
        self.label_ip.setText(_translate("MainWindow", "ip"))
        self.label_port.setText(_translate("MainWindow", "port"))
        self.connect_Button.setText(_translate("MainWindow", "Connect"))
        self.send_Button.setText(_translate("MainWindow", "Send"))
